### ISSUE TITLE
Account already created

### ISSUE THREAD

**Issue by Marcotic** [PatrolServer/bashscanner#10]
Hi!
I ran patrolserver for the first time on a domain i have at home with ddns and this is what i got:
![captura de pantalla de 2017-09-08 11-34-20](https://user-images.githubusercontent.com/29924763/30206135-674f99d8-948b-11e7-80ec-1e08bca17910.png)

It is no me, by the way as it is the first time. Could it be deleted? Or what else can i do?

**Comment by dolfje** [comment]
Hey Marcotic,

You cannot use ddns providers because each domain has to be used only by
one customer.
That is a security measure that we have implemented. Thus you need a
hostname that isn't used and resolves to your server.

Nikos

*USW*
Nikos Verschore
nikos@uwsoftware.be
http://uwsoftware.be
+32(0)476/29.36.64

**Comment by Marcotic** [comment]
Thanks for the reply and excuse me i am earning...
So a url provided by Noip service, pointing to my public ip won't work? Even if this url is only ised by me? 
Thanks and excuses

**Comment by dolfje** [comment]
That is correct,
Tthat will not work, because the url will be *.noip.com. And all urls
ending on noip.com should be of 1 customer.

Nikos

*USW*
Nikos Verschore
nikos@uwsoftware.be
http://uwsoftware.be
+32(0)476/29.36.64

**Comment by Marcotic** [comment]
Thanks a lot.
